services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    expose:
      - 8088
    ports:
      - "80:8088"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/www/todo/static
      - ./media:/app/www/todo/media
      - ./logs:/app/www/todo/logs
    depends_on:
      - todo
  todo:
    build: ./
    image: todo
    container_name: todo
    restart: always
    command: "gunicorn -c gunicorn.py base.wsgi"
    env_file:
      - .env
    expose:
      - "8000"
    links:
      - "postgres:dbtodo"
    networks:
      - dbnet
    volumes:
      - .:/app/www/todo
    depends_on:
      - postgres
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports: 
      - "8888:8080"
    links:
      - "postgres:dbadminer"
    networks: 
      - dbnet
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
